version: '3.8'

services:
  # tesseract:
  #   container_name: tesseract
  #   image: lgdd/tess4j-rest:latest
  #   ports:
  #     - 8080:8000
      
  # solr:
  #   container_name: solr
  #   image: solr
  #   ports:
  #     - 8983:8983
  #   volumes:
  #     - solr_data:/opt/solr/server/solr/ePaperless
  #   entrypoint:
  #     - docker-entrypoint.sh
  #     - solr-precreate
  #     - ePaperless

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=VH3FJ!wKMtFiDv
      - POSTGRES_USER=ePaperless
      - POSTGRES_DB=epaperless_db
    
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v1.7
    ports:
      - 7700:7700
    environment:
      - MEILI_ENV=development
    volumes:
      - meili_data:/meili_data

volumes:
  # solr_data:
  postgres_data:
  meili_data:
